# Generated by Django 5.1.2 on 2024-10-21 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile_Pic'),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile_Pic'),
        ),
        migrations.CreateModel(
            name='BlogManagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(blank=True, choices=[('politics', 'Politics'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('education', 'Education')], max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Media/image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Blog_Management', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('categories', models.CharField(blank=True, choices=[('politics', 'Politics'), ('health', 'Health'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('education', 'Education')], max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Media/image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='NewsPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
