# Generated by Django 5.1.2 on 2024-10-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_creatorprofilemodel_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Followers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofilemodel',
            name='Specialties',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Followers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Interest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Specialties',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
