# Generated by Django 5.1.2 on 2024-10-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_creatorprofilemodel_followers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogManagementModel',
        ),
    ]
